apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc1
spec:
  replicas: 4
  selector:
    app1: web
  template:
    metadata:
      name: "mypod1"
      labels:
        app1: web
    spec:
      containers:
      - name: "myc1"
        image: "vimal13/apache-webserver-php"
